// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7KruBo3n3nSsVDuoQ79r87GOqavd96tY',
    appId: '1:687740103473:web:23e42a93af53e9668bde10',
    messagingSenderId: '687740103473',
    projectId: 'inventory-656dc',
    authDomain: 'inventory-656dc.firebaseapp.com',
    storageBucket: 'inventory-656dc.firebasestorage.app',
    measurementId: 'G-SY34CMRJKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmEC3DrMNatgqqIlTwD_0L3qZDZZEL00E',
    appId: '1:687740103473:android:0a70e74ce8aadcc48bde10',
    messagingSenderId: '687740103473',
    projectId: 'inventory-656dc',
    storageBucket: 'inventory-656dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZD5zXB9fjmpjBa4fAijJdtStjrx1jEb4',
    appId: '1:687740103473:ios:a3f9356d15fbb6058bde10',
    messagingSenderId: '687740103473',
    projectId: 'inventory-656dc',
    storageBucket: 'inventory-656dc.firebasestorage.app',
    iosBundleId: 'com.armanmaurya.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZD5zXB9fjmpjBa4fAijJdtStjrx1jEb4',
    appId: '1:687740103473:ios:14225243434cfece8bde10',
    messagingSenderId: '687740103473',
    projectId: 'inventory-656dc',
    storageBucket: 'inventory-656dc.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7KruBo3n3nSsVDuoQ79r87GOqavd96tY',
    appId: '1:687740103473:web:305ec42481b68f268bde10',
    messagingSenderId: '687740103473',
    projectId: 'inventory-656dc',
    authDomain: 'inventory-656dc.firebaseapp.com',
    storageBucket: 'inventory-656dc.firebasestorage.app',
    measurementId: 'G-12297DLSSH',
  );

}